### PR TITLE
Update SingleValuesPanel.java

### PR DESCRIPTION
**Pull request by ma15569**
Restore original code as it was not able to retrieve any previously preset style

### CODE REVIEW

**Comment by edeso** [comment]
is that really needed? why?

i commented the condition because it failed to redo the styling as soon as one was applied already.

**Comment by ma15569** [comment]
In my test, if I generated a raster layer with its  style (for instance the tool RasterTool-HydrologycTools-flow accumulation generates a layer and applies a style ). Then,  when I open the style panel, it shows again a preset style.
 Anyhow I am going to do other tests with the new buid and check if it is really worth to make the commit

**Comment by ma15569** [comment]
Hi Ede, I am camping for holidatys with a bed connection (working only at this hour of the day).  Yes, I did some tests with the up-to-come 2.3.0 and _everything seems to work fine._  
Previously, the changes seemed not to preserve the style (single values) if it was applied to a layer.  I do not undestand why.

**Comment by ma15569** [comment]
HI Ede, I made some upgrades on language files of raster framework. And also I modified the raster dialog in order to avoid that OJ freezes if user try to apply to a raster style with single values if the raster has more that 2048 values (seems a valid limit in my tests)

**Pull request closed without merging**
