### PR TITLE
Heatmap style

### PR DESCRIPTION
**Pull request by ma15569**
<execution>
                    <id>PLUS-install-raster_tools</id>
                    <goals>
                      <goal>wget</goal>
                    </goals>
                    <configuration>
                      <url>https://sourceforge.net/projects/opensit/files/Openjump/PlugIn/Raster%20Tools/RasterTools-2.0.3-28112022.jar/download</url>
                      <sha1>17443c1aa8e0b7e67d50f3c8da49c9a0c70b77f6</sha1>
                      <unpack>false</unpack>
                      <outputDirectory>${plus.folder}</outputDirectory>
                    </configuration>
                  </execution>

### CODE REVIEW

**Comment by edeso** [comment]
yeah. no. that looks wrong. you seem to have based your changes on some outdated '**heatmap**' branch.

better start with branch **main** of a current clone/fork. read here e.g. 
https://www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/
they do it step by step
.

**Comment by ma15569** [comment]
I Ede,
the info you sent me seems available only for Linux ( I actually use
windows).
Anyhow  I don't understand if the pull request I did some hours ago was Ok
or not:

[image: immagine.png]


Il giorno mer 30 nov 2022 alle ore 14:20 edeso ***@***.***>
ha scritto:

**Comment by edeso** [comment]
@ma15569 well the steps are generally the same, on any platform. it was just the first example i could find. fell free to search for yourself ;)

wrt. to your [other PR](https://github.com/openjump-gis/openjump/pull/77).  i added comments in there and renamed to a speaking title. please read and adapt there.

**Comment by ma15569** [comment]
Ok. I will try with GitHub Desktop, tomorrow
Peppe

Il giorno mer 30 nov 2022 alle ore 17:22 edeso ***@***.***>
ha scritto:

**Pull request closed without merging**
