### PR TITLE
Update Bundle.properties

### PR DESCRIPTION
**Pull request by ma15569**

### CODE REVIEW

**Comment by kijato** [comment]
May I ask, what is the role of this file next to Bundle_en.properties? I can see that they are not the same, but I don't understand the reason for the difference.

**Comment by edeso** [comment]
@kijato good catch. the "_en" file is obsolete. as english is the fallback language anyway it is not needed. i removed it.

**Comment by edeso** [comment]
feel free to look yourself :)

afais it just had some double keys that were empty and generally seemed older.

**Comment by kijato** [comment]
You're right, really I didn't check the duplicate keys, it was just a big difference in file size that was strange.

**Pull request closed without merging**
